### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by justbill2020** [evancohen/smart-mirror#642]
- [ ] fix 'show debug' command
https://github.com/evancohen/smart-mirror/blob/dev/app/js/controller.js#L156-L159
```JavaScript
SpeechService.addCommand('debug', function () {
	console.debug("Boop Boop. Showing debug info...");
	$scope.debug = true;
});
```

- [ ] autoupdate commands pagination if focus is 'commands'. then create a refresh command in controller and trigger maybe?
https://github.com/evancohen/smart-mirror/blob/dev/plugins/speech/service.js#L80
```JavaScript
if (Focus.get()=='commands') {
   service.getCommands()
}
```

- [ ] also fix path for config.general.commandsperpage
https://github.com/evancohen/smart-mirror/blob/dev/plugins/speech/service.js#L92

**Comment by evancohen** [comment]
We should get rid of the debug info command - it's basically useless.

**Comment by justbill2020** [comment]
That was kinda how I was gonna fix it lol

**Comment by justbill2020** [comment]
- [ ] maybe.... create enable/disable config for each plugin
- [ ] maybe.... create index.js which dynamically renders index.html by polling folders for index.html files... and maybe even js files so that we can dynamically render new plugins automatically allowing for dynamic plugins...

**Comment by evancohen** [comment]
should we merge these fixes?

**Comment by sdetweil** [comment]
> * [ ]  maybe.... create enable/disable config for each plugin
> * [ ]  maybe.... create index.js which dynamically renders index.html by polling folders for index.html files... and maybe even js files so that we can dynamically render new plugins automatically allowing for dynamic plugins...
> 
> i know in my head how i want to do this but we shall see...

funny, I never saw this til now

this is exactly what my plugin config does!!
